### ISSUE TITLE
I also put the ops3 in automatic and it is not controlled and I cannot make landings in the vace edwuards

### ISSUE THREAD

**Issue by GAMETROX50** [giuliodondi/kOS-Shuttle-OPS3#11]

**Comment by giuliodondi** [comment]
Use the description box instead of writing a poem in the title. Add details on what situation you were in, you did, what you expected to happen and what you see, with screenshots. 
I'm in no condition to give assistance like this.

**Comment by GAMETROX50** [comment]
ok but the last thing is that I want to know why when I run ops3_deorbit it says that the program ended and how i can fix it

**Comment by giuliodondi** [comment]
1- please do not comment in reference to another issue from here. Mixing things up doesn't help anyone. You can add comments on a closed issue, you know.

2- If you go back to the other issue you are referencing, you'll find I highlighed in bold and italic exactly what to do to fix the problem I think you're having. If you don't understand what you are supposed to do, I already instructed you to look up the Principia tutorials. This is not a generic helpdesk.

**Comment by giuliodondi** [comment]
That aside:

> I also put the ops3 in automatic and it is not controlled and I cannot make landings in the vace edwuards

if you still require help about **_this issue and no other issue_** I'm going to need you to add details and screenshots of your situation because I have nothing to work on. As I already said above.

**Comment by GAMETROX50** [comment]
Uploading 20241113-2248-51.1954318.mp4…

**Comment by GAMETROX50** [comment]
![Captura de pantalla 2024-11-13 195057](https://github.com/user-attachments/assets/2da545dc-b368-424a-9018-81c1edd7f059)
i write ops3 and this happen

**Comment by GAMETROX50** [comment]
revise la carpeta de ops3 y esto encontre no se si esta bein esta configuracion
![Captura de pantalla 2024-12-14 163424](https://github.com/user-attachments/assets/b39f6068-810e-4521-92c4-654582b784d3)
