### ISSUE TITLE
Tried tu use and got error 

### ISSUE THREAD

**Issue by FantomasicPlay** [giuliodondi/kOS-Shuttle-OPS3#12]
![KSP_x64_4c6PyU9RQJ](https://github.com/user-attachments/assets/f9aa310a-f87b-4c8d-abfa-c9311cc7666f)

**Comment by giuliodondi** [comment]
![image](https://github.com/user-attachments/assets/b5a71fa0-cc0d-4852-8c20-83ece67b77c0)

The error is telling you the program cannot find the body flap part. Sure enough, you forgot to put it.
