### ISSUE TITLE
hello giulio

### ISSUE THREAD

**Issue by GAMETROX50** [giuliodondi/kOS-Shuttle-OPS3#16]
my ops3 deorbit does not work normally in the kos console I put switch to 0. run ops3_deorbit.ks or just ops3_deorbit. but no matter which way the script doesn't work, I'll leave you a screenshot
![Captura de pantalla 2024-12-18 135225](https://github.com/user-attachments/assets/48d40b2a-994c-4354-a847-ddc63187e4fd)

**Comment by giuliodondi** [comment]
please update the scripts to the latest version. 
I fixed the error logging so now the script should tell you exactly what's wrong. 
Spoiler: you need to have engines on before running it
