### ISSUE TITLE
rng not working

### ISSUE THREAD

**Issue by glichdude2011** [giuliodondi/kOS-Shuttle-OPS3#17]
I try to put everything in order with principia but the rng does not turn green all the time it is red I will leave you a screenshot
![imagen_2024-12-19_114852979](https://github.com/user-attachments/assets/f2caabe8-f490-4557-92fa-7782ed867797)

**Comment by giuliodondi** [comment]
It's red because it's off by 2000km.
You need to move the manoeuvre node closer to the site, and then readjust.
