### ISSUE TITLE
problem with ops3

### ISSUE THREAD

**Issue by GAMETROX50** [giuliodondi/kOS-Shuttle-OPS3#18]
Hello Giulio, I have a problem with ops3 to land the shuttle, it does not recognize the landing site and it simply goes anywhere very close to the KSC. I tried to use the measurerwy command to make the landing site and when I did it I could not launch the ship due to a problem. from ops1 and I don't understand what I can do
![Captura de pantalla 2024-12-23 230003](https://github.com/user-attachments/assets/844650b4-3c32-49a3-8dc2-721ce2d85bc8)

**Comment by giuliodondi** [comment]
[Full demonstration video from start to finish](https://www.youtube.com/watch?v=5ozDtFUTUwY&ab_channel=RaizSpace) .

Please use this issues page to post bugs and things breaking or not working as intended. Not for requests for help
