### ISSUE TITLE
The space shuttle loses stability during flight

### ISSUE THREAD

**Issue by Nemo2507** [giuliodondi/kOS-Shuttle-OPS3#3]
so i run OPS3 as normal and most of the flight when fine until around 65 km where it banks 90 degrees and when the guidance commands to to bank less it just loses control
![image](https://github.com/giuliodondi/kOS-Shuttle-OPS3/assets/143341029/e4e8fe72-35e6-472d-9a0f-70f04fc34050)

**Comment by Nemo2507** [comment]
i noticed that when the guidance switch to ENTRY TRAJ 3 the DAP banks extremely hard to the opposite of where the guidance is aiming, i tried to take over manual control but it just wasnt enough

**Comment by giuliodondi** [comment]
It seems to me  the issue is not with the script but with your craft, incorrect cg can cause all sorts of instability and saturate the rcs.

You need to provide more information on exactly which entry interface conditions you encountered and what was your OMS/RCS tank quantity, also what payload you carried and  how it was placed

**Comment by Nemo2507** [comment]
The RCS was not saturate at all the for the OMS tank i have around 70% of propellant (i transferred the fuel from the front) and i didnt have any payload

**Comment by giuliodondi** [comment]
By saturation I mean the control range, if the inputs are maxed (saturated) then your craft is simply in a condition too unstable for the script to control.

70% of OMS quantity is far too much, especially if it's all at the back. 40% is even stretching it, try to aim for a quarter

**Comment by Nemo2507** [comment]
Can i just dump the fuel using ship manifest? Also check your fork of the space shuttle issues the texture on the ET is bugged or something

**Comment by giuliodondi** [comment]
You can write me on discord at at dolin4214 .

In any case, I never encountered the steering isues you describe, I've done some pushes to reduce the coupling between roll and pitch during HDG phase in some edge cases but roll was always very responsive.
I'm going to need some debug logs or at the very least a series of screenshots to figure out what's going on

**Comment by Nemo2507** [comment]
Ill run another test and record the log with some screenshots during the flight

**Comment by Nemo2507** [comment]
[ops3_log.csv](https://github.com/giuliodondi/kOS-Shuttle-OPS3/files/14557096/ops3_log.csv)

i didnt take screenshots but i did record a video during where the problem starts check discord
