### ISSUE TITLE
Error code when launching OPS3

### ISSUE THREAD

**Issue by 1waverider** [giuliodondi/kOS-Shuttle-OPS3#5]
(https://github.com/giuliodondi/kOS-Shuttle-OPS3/assets/170385302/6e17d0fb-eba7-48d0-b9f5-797c20acd5f0)

Conditions:
Atmosphere Autopilot is not installed
The rudder that I used is the Shuttle Rudder Panel
In Entry Interface, below 122km
KOS is functional
Script is in the correct location

The error code it spits out, after attempting to run OPS3 is

Index out of range. Must be non-negative and less than the size of the collection. Parameter name: index 
At 0:/Shuttle_OPS3/src/ops3_control_utility.ks line 402
local ruddermods is SHIP:PARTSDUBBED("ShuttleTailControl")[0]:MODULESNAMED("ModuleControlSurface")

and also, below it,

LOCAL aerosurfaces_control IS aerosurfaces_control_factory().

Do I need to change my control surface?

**Comment by giuliodondi** [comment]
yes, you need to use the rudder part named "ShuttleTailControl".

It occurs to me only now that the other  "Rudder Panel" part will always cause this error, it's an old experimental part that never ended up working right. Apologies for this

**Comment by 1waverider** [comment]
I switched to "Shuttle Tail Control" and got a different, but similar error when running it

"Tried to push Infinity into the stack"

and also

"Error, not enough rudder control modules found"

**Comment by giuliodondi** [comment]
- please verify that, indeed, Atmospheric Autopilot is **NOT** installed
- right-click on the tail control part to show the context menu and post a screenshot
- spawn the vehicle, open a kOS terminal and run the following commands:
`clearscreen. print ship:partsdubbed("ShuttleTailControl")[0]:modules.`
and post another screenshot with the output. Please enlarge the terminal and make sure the command output is not truncated

**Comment by 1waverider** [comment]
I'm very confident in the fact that Atmospheric autopilot is not installed, I've looked through my install files 


(https://github.com/giuliodondi/kOS-Shuttle-OPS3/assets/170385302/d88226d6-9368-481f-98a2-d9a95b1186e1)

(https://github.com/giuliodondi/kOS-Shuttle-OPS3/assets/170385302/0bac8b2c-f193-4ea6-8cb1-f1b50c72223a)

**Comment by giuliodondi** [comment]
your Space Shuttle System installation is broken.

I can see that from the second screenshot, you have 2 B9 part switch modules while there should be just the one, and you have Ferram configs which I removed long ago

**Comment by 1waverider** [comment]
Do I delete "FARShuttleAerodynamicModel'?

**Comment by 1waverider** [comment]
Update:
(https://github.com/giuliodondi/kOS-Shuttle-OPS3/assets/170385302/c22b4528-136f-4d58-894f-e3c48b11055d)
I changed my KOS addons, ran the "list the control modules" command and thats what it gave me. Is this good?

**Comment by giuliodondi** [comment]
No, deleting thode dlls is **not** how you fix that problem. Those dlls are needed.
I suspect that you have two sets of Realism Overhaul configs for the shuttle that clash, but it's impossible to tell for sure.

I suggest you clean up everything related to the Space Shuttle and start over. Read the README installation instructions very carefully.
If your installation troubles persist, please open up an issue in the SpaceShuttleSystem fork repository.

Since we are now dealing with a different issue that does not concern the OPS3 script, I will close this thread for the moment.
You can still comment after closure and, if the problem persists, I'll re-open it
