### ISSUE TITLE
Shuttle struggling to line up with Runway

### ISSUE THREAD

**Issue by GlebKerman** [giuliodondi/kOS-Shuttle-OPS3#6]
Hi, the script is struggling to line up with the runway after the HAC, the runway parameters were measured using your measurerwy.ks script, and after each attempt with Ops3 I went back and re-measured the runway. This was attempted with the start location for the measurement being changed occasionally between attempts ie. the 1st attempt was measured from the very end of Runway 33 to around 4/5s of the way to the other end, the 2nd and 3r attempts were measured from the 2nd Centre Line marking after the touchdown point (Rwy 33 End) to 4/5s of the way to the Rwy 15 end. The Shuttle still struggles to line up with the runway, often flaring far too late or trying to make a last minute side-slip type movement to line up.

Video from attempt 3:

https://github.com/giuliodondi/kOS-Shuttle-OPS3/assets/147939419/a8ca92c0-e3b3-4375-a989-18590025452e

Some of the values I tried in the script (measured values):

![image](https://github.com/giuliodondi/kOS-Shuttle-OPS3/assets/147939419/724c88e7-a895-40b5-adab-a8baa7f5103c)

**Comment by giuliodondi** [comment]
yes I had already seen the problem on my end. 

I pushed some fixed to the control gains that ought to solve your issue, try to pull thge latest and let me know

**Comment by GlebKerman** [comment]
Will let you know as soon as I can, appreciate the help!

**Comment by GlebKerman** [comment]
Tried it with the latest version, with the values from the original landing_sites.ks shown in the above screenshots:


https://github.com/giuliodondi/kOS-Shuttle-OPS3/assets/147939419/9bfbec4e-f08c-4dc2-a320-0d5f17ac9d7d

Having to heavily compress these videos I do apologise for the quality

**Comment by giuliodondi** [comment]
This issue has been reported by several users but so far I've never been able to reproduce it.
One user reports it might be related to the Trajectories mod, do you have it installed? If so, which version, and how is it configured?
Could you also try to see if removing the mod helps any?

**Comment by GlebKerman** [comment]
I have Trajectories v2.4.5 installed at the moment, I got the mod for using your ops1 scripts, as for the settings:

![unknown_2024 06 08-23 24](https://github.com/giuliodondi/kOS-Shuttle-OPS3/assets/147939419/0c941686-20c1-4d1c-9ceb-b1b8deb1cd92)
![unknown_2024 06 08-23 24_1](https://github.com/giuliodondi/kOS-Shuttle-OPS3/assets/147939419/353f3d4f-53fa-41ef-8d14-49c1a5ffbd53)

**Comment by GlebKerman** [comment]
Will let you know how removing it affects the script

**Comment by GlebKerman** [comment]
Hey, I remeasured the runway and removed trajectories and it managed touchdown on the runway!

**Comment by giuliodondi** [comment]
Huh... interesting,  will need to investigate further, thanks for the report in the meantime!

**Comment by GlebKerman** [comment]
https://github.com/giuliodondi/kOS-Shuttle-OPS3/assets/147939419/14d19756-f023-4d0a-bcc0-453618b28ac5

Of course! Do you know any alternatives to Trajectories to help with the maneouvre nodes for entry?

**Comment by giuliodondi** [comment]
Principia is by far the best

**Comment by GlebKerman** [comment]
Yeah I was genuinely surprised at just how smooth that was. Script works amazingly well!

Appreciate the recommendation of Principia also!
