### ISSUE TITLE
ops3_deorbit closing when selecting a landing site with manoeuvre node creatde

### ISSUE THREAD

**Issue by GlebKerman** [giuliodondi/kOS-Shuttle-OPS3#7]
Hi, I made a principia manoeuvre node with a perigee around 20km nearby to the KSC, when running ops3_deorbit and selecting any landing site the scrip closes itself.

https://github.com/giuliodondi/kOS-Shuttle-OPS3/assets/147939419/14f17218-454b-4fd4-93f3-18d632868ca7

**Comment by GlebKerman** [comment]
Hey quick update, I did 2 things at once to make it work. 

-I quicksaved and loaded the save
-I selected "Show on Navball" for the principia node 

I don't know which of these made it work again but something did the trick

**Comment by giuliodondi** [comment]
> I selected "Show on Navball" for the principia node

definitely this.

I didn't have time to get on this and test things out. Nevertheless I know that if you don't enable that the node does not appear as a KSP node and the script probably doesn't pick it up.
I should probably overhaul the script to add an error message for this case

**Comment by GlebKerman** [comment]
Ahh alright, thanks for clearing it up! Will remember this in future!

**Comment by GlebKerman** [comment]
Appreciate the work!
